### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by giasemidis** [rossheat/uk-latest-news-chatgpt-plugin#1]
I am trying to use the plugin programmatically using langchain agents, but I am getting authentication error. How can I provide a service access token? It's not clear from the instructions in the readme doc.

```
os.environ["OPENAI_API_KEY"] = "<VALID KEY>"
llm = ChatOpenAI(temperature=0)
json_url = "https://gptnews.uk/.well-known/ai-plugin.json"
tool = AIPluginTool.from_plugin_url(json_url)

tools = load_tools(["requests_all"])
tools += [tool]

agent_chain = initialize_agent(
    tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True
)
agent_chain.run("What is the latest news?")
```
returns:
```
`I am unable to access the latest news stories without authorization.`
```

**Comment by rossheat** [comment]
The endpoints listed in https://gptnews.uk/.well-known/ai-plugin.json require a secret authorization token. This is to ensure that only OpenAI can use them.

If you wish to use the plugin's functionality outside of the official ChatGPT web app, you will need to host it yourself; include an `Authorization: Bearer <token>` header in each API request. The `<token>` should match the `SERVICE_ACCESS_TOKEN` value you specify in the `.env.local` configuration file.
